### ISSUE TITLE
Vr.html 无法运行，请问是需要设备吗？

### ISSUE THREAD

**Issue by yspisgod** [LittleWhitechun/WebglHomeFurnishing#1]
a-scene.js:84 Uncaught TypeError: Cannot read properties of null (reading 'classList')
    at HTMLElement.value (a-scene.js:84:23)
    at HTMLElement.value (a-scene.js:74:14)
    at HTMLElement.value (a-scene.js:59:14)
    at HTMLElement.value (a-register-element.js:150:28)
    at v (document-register-element.js:2:1089)
    at HTMLDocument.r.createElement (document-register-element.js:2:5629)
    at vr.html:14:30

这个是报错信息

**Comment by LittleWhitechun** [comment]
不需要设备也可以的。
这里应该是创建a-scene元素的时候报错了，可以看一下aframe.min.js有没有成功引入，或者试试用新版的aframe.min.js

**Comment by yspisgod** [comment]
我用浏览器控制台看了，是有加载成功的
也用了最新版本的1.3.0
还是不行啊！
这边代码我都没改动过，还有其他思路没 ，望指教

**Comment by yspisgod** [comment]
不好意思，没刷新，可以了
